---
- name: Check ping
  ping:


#- name: Install Nginx
#  apt: pkg=nginx state=installed update_cache=false
#
#
#- name: Install RabbitMQ
#  apt: pkg=rabbitmq-server=3.3.5-1 state=installed update_cache=false
#
#
#- name: Install Redis
#  apt: pkg=redis-server=2.8.17-2 state=installed update_cache=false
#
#
#- name: Install Tomcat
#  apt: pkg=tomcat7 state=installed update_cache=false
#


- name: Copy msg_agent
  copy: src=msg_agent dest=/datayes/

- name: Copy gateway
  copy: src=gateway dest=/datayes/
  register: cpstat

- name: Setup gw properties file
  #when: cpstat|success
  template: src=gateway.properties_tpl dest=/datayes/gateway/etc/gateway.properties





