---

#- name: Install JDK7_71
#  copy: src=jdk-7u71-linux-x64.gz dest=/usr/java/ owner=root group=root
#  notify:
#    - Install jdk7u71
#    - Change jdk owner
#    - Backup profile
#    - Copy profile


#- name: Install mysql
#  apt: pkg=mysql state=installed update_cache=true
#  notify: Start mysql
#
#
#- name: Copy schema sql
#  copy: src=sql dest=/opt
#  notify:
#    - Create usermaster schema
#    - Create mobilemaster schema
#    - Create message schema
#    - Create cloud schema
#    - Add user paas


#- name: Install Nginx
#  apt: pkg=nginx state=installed update_cache=false
#  notify:
#    - Copy ngx config
#    - Copy web content
#
#
#- name: Copy msg_agent
#  copy: src=msg_agent dest=/datayes/
#  notify: Copy msg script
#
#
#- name: Copy gateway
#  copy: src=gateway dest=/datayes/
#  register: cpstat
#  notify: Copy gw script
#
#
#- name: Setup gw properties file
#  when: cpstat|success
#  template: src=app/gateway/gateway.properties_tpl dest=/datayes/gateway/etc/gateway.properties






#- name: Install RabbitMQ
#  apt: pkg=rabbitmq-server=3.3.5-1 state=installed update_cache=false
#
#
#- name: Create Vhosts in MQ
#  rabbitmq_vhost: name={{ item }} state=present
#  with_items: 
#      - /session  
#      - /usermaster
#      - /gateway
#      - /message
#
#
#- name: Add user usermaster
#  rabbitmq_user: user=usermaster
#                 password=usermaster_pass
#                 vhost=/usermaster
#                 configure_priv=.*
#                 read_priv=.*
#                 write_priv=.*
#                 state=present
#
#
#- name: Add user message
#  rabbitmq_user: user=message
#                 password=message_pass
#                 vhost=/message
#                 configure_priv=.*
#                 read_priv=.*
#                 write_priv=.*
#                 state=present
#
#
#- name: Add user gateway
#  rabbitmq_user: user=gateway
#                 password=gateway_pass
#                 vhost=/gateway
#                 configure_priv=.*
#                 read_priv=.*
#                 write_priv=.*
#                 state=present
#
#
#- name: Add user session
#  rabbitmq_user: user=session
#                 password=session_pass
#                 vhost=/session
#                 configure_priv=.*
#                 read_priv=.*
#                 write_priv=.*
#                 state=present





#- name: Install Redis
#  apt: pkg=redis-server=2.8.17-2 state=installed update_cache=false
#
#
#
#- name: Send redis data
#  copy: src=rds_data dest=/opt
#  notify: 
#    - Import cfg into redis db0 
#    - Register usermaster
#    - Register usermaster ignore
#    - Import token into redis db1
#    - Import permission into redis db2



#- name: Install tomcat7
#  apt: pkg=tomcat7 state=installed update_cache=false
#  notify:
#    - Copy app cfg
#    - Copy cataliana shell script
#    - Copy catalian properties
#    - Copy webapps




- name: Copy app cfg
  copy: src=tomcat/{{ item }} dest=/etc/tomcat7/Catalina/localhost/
  with_items:
    - api.xml
    - usermaster.xml
    - webmail.xml

- name: Copy cataliana shell script
  copy: src=tomcat/catalina.sh  dest=/usr/share/tomcat7/bin/


- name: Copy catalian properties
  copy: src=tomcat/catalina.properties  dest=/etc/tomcat7/


- name: Copy webapps
  copy: src=webapps  dest=/datayes/
