---

- name: Install jdk7u71
  shell: tar xvf /usr/java/jdk-7u71-linux-x64.gz -C /usr/java/


- name: Change jdk owner
  shell: chown root:root -R /usr/java/jdk1.7.0_71


- name: Backup profile
  shell: mv /etc/profile /etc/profile_bak

- name: Copy profile
  copy: src=profile dest=/etc/


- name: Copy msg script
  copy: src=upstart/cloud-msg-agent.conf  dest=/etc/init/

- name: Copy gw script
  copy: src=upstart/cloud-gateway.conf  dest=/etc/init/


- name: Start nginx
  service: name=nginx state=started


- name: Start mysql
  service: name=mysql state=started


- name: Create usermaster schema
  when:
  shell: /opt/mysql/server-5.6/bin/mysql < /opt/sql/vpcgw_um.sql


- name: Create mobilemaster schema
  shell: /opt/mysql/server-5.6/bin/mysql < /opt/sql/vpcgw_mm.sql


- name: Create message schema
  shell: /opt/mysql/server-5.6/bin/mysql < /opt/sql/vpcgw_msg.sql


- name: Create cloud schema
  shell: /opt/mysql/server-5.6/bin/mysql < /opt/sql/vpcgw_cloud.sql


- name: Add user paas
  shell: /opt/mysql/server-5.6/bin/mysql < /opt/sql/adduser.sql


- name: Copy ngx config
  template: src={{ item }} dest=/etc/nginx/sites-enabled/
  with_items:
      - ngx/app.conf
      - ngx/gateway.conf
      - ngx/achilles.conf

- name: Copy web content
  copy: src=web dest=/datayes/



- name: Import cfg into redis db0
  shell: cat /opt/rds_data/rds_gwcfg | redis-cli --pipe

- name: Register usermaster 
  shell: cat /opt/rds_data/rds_gwum | redis-cli --pipe

- name: Register usermaster ignore
  shell: cat /opt/rds_data/rds_gwumigr | redis-cli --pipe


- name: Import token into redis db1
  shell: cat /opt/rds_data/rds_gwtoken | redis-cli -n 1 --pipe


- name: Import permission into redis db2
  shell: cat /opt/rds_data/rds_gwpermission | redis-cli -n 2 --pipe


- name: Copy app cfg
  copy: src=tomcat/{{ item }} dest=/etc/tomcat7/Catalina/localhost/
  with_items: 
    - api.xml
    - usermaster.xml
    - webmail.xml

- name: Copy cataliana shell script
  copy: src=tomcat/catalina.sh  dest=/usr/share/tomcat7/bin/


- name: Copy catalian properties
  copy: src=tomcat/catalina.properties  dest=/etc/tomcat7/


- name: Copy webapps
  copy: src=webapps  dest=/datayes/



